import { AVAILABLE_BURGER_INGREDIENT_INGREDIENTS } from './components';

const BURGER_INGREDIENTS_BASE_URL = 'burger-ingredients';

export { AVAILABLE_BURGER_INGREDIENT_INGREDIENTS, BURGER_INGREDIENTS_BASE_URL };